### ISSUE TITLE
How I can verify this attack in my android smartphone by using this script?

### ISSUE THREAD

**Issue by jiajiajiajiajiajiajiajia** [chinatso/KRACK#1]
Hi
I want to verify KRACK in my android smartphone
I have saw the  demonstration video in krack website, in this video, krack-all-zero-tk.py script has been used to verify this attack
How I can verify it by using your script "krack-all-zero-tk.py "?

Thanks

**Comment by STCNO** [comment]
You have clearly not read the docs page. The code isn't released, yet.
Please close. This isn't even the original repository anyway.

**Comment by jiajiajiajiajiajiajiajia** [comment]
OK .I know, Thanks
